version: '3'

services:
  carla-novnc-1:
    build: .
    image: carla-novnc
    container_name: carla-novnc-1
    ports:
      - "6081:80"
    volumes:
      - ${PWD}/carla-1:/workspace:rw
      - ${PWD}/carla-all:/carla:r
    environment:
      - USERNAME=carla
      - USERID=1000
      - RESOLUTION=1280x720
      - HTTP_PASSWORD=smartcity
    networks:
      - carla-clients
    restart: unless-stopped

  carla-novnc-2:
    build: .
    image: carla-novnc
    container_name: carla-novnc-2
    ports:
      - "6082:80"
    volumes:
      - ${PWD}/carla-2:/workspace:rw
      - ${PWD}/carla-all:/carla:r
    environment:
      - USERNAME=carla
      - USERID=1000
      - RESOLUTION=1280x720
      - HTTP_PASSWORD=smartcity
    networks:
      - carla-clients
    restart: unless-stopped

  carla-novnc-3:
    build: .
    image: carla-novnc
    container_name: carla-novnc-3
    ports:
      - "6083:80"
    volumes:
      - ${PWD}/carla-3:/workspace:rw
      - ${PWD}/carla-all:/carla:r
    environment:
      - USERNAME=carla
      - USERID=1000
      - RESOLUTION=1280x720
      - HTTP_PASSWORD=smartcity
    networks:
      - carla-clients
    restart: unless-stopped

  carla-novnc-4:
    build: .
    image: carla-novnc
    container_name: carla-novnc-4
    ports:
      - "6084:80"
    volumes:
      - ${PWD}/carla-4:/workspace:rw
      - ${PWD}/carla-all:/carla:r
    environment:
      - USERNAME=carla
      - USERID=1000
      - RESOLUTION=1280x720
      - HTTP_PASSWORD=smartcity
    networks:
      - carla-clients
    restart: unless-stopped

  carla-novnc-5:
    build: .
    image: carla-novnc
    container_name: carla-novnc-5
    ports:
      - "6085:80"
    volumes:
      - ${PWD}/carla-5:/workspace:rw
      - ${PWD}/carla-all:/carla:r
    environment:
      - USERNAME=carla
      - USERID=1000
      - RESOLUTION=1280x720
      - HTTP_PASSWORD=smartcity
    networks:
      - carla-clients
    restart: unless-stopped

  carla-novnc-6:
    build: .
    image: carla-novnc
    container_name: carla-novnc-6
    ports:
      - "6086:80"
    volumes:
      - ${PWD}/carla-6:/workspace:rw
      - ${PWD}/carla-all:/carla:r
    environment:
      - USERNAME=carla
      - USERID=1000
      - RESOLUTION=1280x720
      - HTTP_PASSWORD=smartcity
    networks:
      - carla-clients
    restart: unless-stopped

  carla-novnc-7:
    build: .
    image: carla-novnc
    container_name: carla-novnc-7
    ports:
      - "6087:80"
    volumes:
      - ${PWD}/carla-7:/workspace:rw
      - ${PWD}/carla-all:/carla:r
    environment:
      - USERNAME=carla
      - USERID=1000
      - RESOLUTION=1280x720
      - HTTP_PASSWORD=smartcity
    networks:
      - carla-clients
    restart: unless-stopped

networks:
  carla-clients:
    driver: bridge
